CC = g++



all: chandra cyclic economic gaukwa katsura noon prism


chandra: chandra.cpp
	$(CC)  chandra.cpp  -o  chandra

cyclic: cyclic.cpp
	$(CC)  cyclic.cpp  -o  cyclic

economic: economic.cpp
	$(CC)  economic.cpp  -o  economic

gaukwa: gaukwa.cpp
	$(CC)  gaukwa.cpp  -o  gaukwa

katsura: katsura.cpp
	$(CC)  katsura.cpp  -o  katsura

noon: noon.cpp
	$(CC)  noon.cpp  -o  noon

prism: prism.cpp
	$(CC)  prism.cpp  -o  prism


clean:
	/bin/rm -f *.o *~ chandra cyclic economic gaukwa katsura noon prism
